// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DocumentsViewer: typeof import('./src/components/DocumentsViewer/index.vue')['default']
    DocumentsViewerFilter: typeof import('./src/components/DocumentsViewer/Filter.vue')['default']
    DocumentsViewerIndustryFilter: typeof import('./src/components/DocumentsViewer/IndustryFilter.vue')['default']
    DocumentsViewerOptions: typeof import('./src/components/DocumentsViewer/Options.vue')['default']
  }
}

export {}
